export const zh = {
  brand: "Resonance Archive",
  brandZh: "共鸣档案",
  name: "Huaxin Zhang",
  nameZh: "张铧心",
  tagline: "把复杂流程做成能上手、能验证的作品。",
  profile: "游戏策划 × AI 产品设计。用用户研究、系统策划和可运行原型，把一句设想推进到能交付的作品。",
  coreAreas: [
    "游戏系统与关卡策划",
    "AI Agent 工作流",
    "互动原型与用户研究",
    "内容运营与跨文化沟通",
  ],
  entry: {
    play: "进入演奏",
    explore: "浏览作品",
    continue: "继续",
    soundOn: "开启声音",
    soundOff: "关闭声音",
    reducedMotion: "减少动效",
    howToPlay: "如何游玩",
    credits: "制作名单",
    hint: "五个项目就是五个独立关卡，从一开始全部开放。",
  },
  howToPlay: {
    title: "如何游玩",
    body: [
      "D / F / 空格 / J / K，五键对应五轨",
      "在节拍点上击键，角色不再需要提前移动",
      "长音按住对应键",
      "E 键在“记忆”段打开项目档案",
      "Esc 暂停",
      "角色随成功击键移动，作为视觉反馈",
      "Miss 只让世界变淡，不打断乐章",
      "连击逐步显影上方记忆长卷",
    ],
  },
  credits: {
    title: "制作名单",
    body: [
      "共鸣档案 · 张铧心互动作品集",
      "五个 Csikos Post 录音版本，分别塑造五种关卡风格",
      "技术：Next.js、Phaser 3、Web Audio",
    ],
  },
  hud: {
    pause: "暂停",
    resume: "继续",
    sound: "声音",
    archive: "档案",
    skip: "跳过章节",
    assist: "辅助",
    explore: "浏览",
    combo: "连击",
    memory: "记忆",
  },
  chapters: {
    prologue: "序章",
    "movement-i": "第一乐章 · Pixel World",
    "movement-ii": "第二乐章 · 雨夜游戏厅",
    "movement-iii": "第三乐章 · IWBTZ",
    "movement-iv": "第四乐章 · 创作工具",
    coda: "尾声",
  },
  narrative: {
    "prologue-1": "每个项目都始于一个信号。",
    "prologue-2": "有些成为系统。",
    "prologue-3": "有些成为世界。",
    "prologue-4": "我把复杂系统做成能感知、能上手、经得起检验的东西。",
    "pixel-1": "故事会被整理成可执行的生产规格，但原本古怪、真实的创意不会因此消失。",
    "pixel-2": "十个 Agent 分工、互审，并在生成前把每个冲突摆到明处。",
    "pixel-3": "世界生成完成后，它鲜亮的封面会直接替换创作器的默认背景。",
    "pixel-4": "成品能被真正玩起来，能保存在本地、随时重开，也能作为离线游戏带走。",
    "browser-1": "你清掉了噪音。",
    "browser-2": "有用的信号一直都在。",
    "browser-3": "我设计浏览器工具，把重复操作收成有目的的工作流。",
    "emotion-1": "不是每个信号都需要被纠正。",
    "emotion-2": "有些需要被听见。",
    "emotion-3": "体贴的系统知道何时回应，也知道何时留白。",
    "research-1": "原始信号很少自我解释。",
    "research-2": "模式在仔细的提问中浮现。",
    "research-3": "研究教会我看见界面之外。",
    "coda-1": "线索回到同一件乐器。",
    "coda-2": "如果这段体验让你想聊点什么，欢迎继续找我。",
  },
  explore: {
    title: "精选作品",
    subtitle: "五个项目，五种把创意做成产品的方法。",
    about: "关于",
    projects: "项目",
    contact: "联系",
    downloadCv: "下载简历",
    playInstead: "演奏作品集",
  },
  contact: {
    email: "hxz439@alumni.bham.ac.uk",
    github: "https://github.com/zbjgrhr",
    cvPath: "/downloads/Huaxin_Zhang_CV_Chinese.pdf",
    portfolioPath: "/downloads/Zhang_Huaxin_Creative_Portfolio.pdf",
  },
  coda: {
    title: "一起做点有意义的事",
    line: "如果这段体验让你想聊点什么，欢迎继续找我。",
    replay: "再演奏一次",
    explore: "浏览项目",
    autoplay: "开启自动演奏",
  },
  archive: {
    close: "关闭档案",
    context: "背景",
    problem: "问题",
    role: "我的角色",
    process: "过程",
    decisions: "关键决策",
    tech: "技术",
    challenges: "挑战",
    outcome: "结果",
    learned: "我学到的",
    links: "链接",
  },
  pauseMenu: {
    title: "已暂停",
    resume: "继续",
    settings: "设置",
    exitExplore: "退出到浏览",
  },
};
