export const zh = {
  brand: "Resonance Archive",
  brandZh: "共鸣档案",
  name: "Huaxin Zhang",
  nameZh: "张铧心",
  tagline: "无聊的部分我们慢慢拆解；留给玩家的，是安心和探索的乐趣。",
  profile: "伯明翰大学人工智能与计算机科学硕士，关注 AI 产品、全栈互动原型、创意技术与导师指导下的多模态研究。",
  coreAreas: [
    "AI 产品系统",
    "全栈互动原型",
    "游戏与创意技术",
    "负责任的多模态研究",
  ],
  entry: {
    play: "进入演奏",
    explore: "浏览作品",
    continue: "继续",
    soundOn: "开启声音",
    soundOff: "关闭声音",
    reducedMotion: "减少动效",
    howToPlay: "如何游玩",
    credits: "制作名单",
    hint: "五个项目成为五个独立关卡；所有关卡从一开始即可自由选择。",
  },
  howToPlay: {
    title: "如何游玩",
    body: [
      "D / F / 空格 / J / K — 五个按键分别直接对应五条轨道",
      "在节拍上直接击键 — 命中前不再需要移动角色",
      "按住对应按键 — 延续长音",
      "E — 在「记忆」段打开项目档案",
      "Esc — 暂停",
      "角色会跟随成功击键移动，作为视觉反馈。",
      "Miss 只会让世界变淡，不会中断乐章。",
      "连击会让上方记忆长卷逐步显影。",
    ],
  },
  credits: {
    title: "制作名单",
    body: [
      "共鸣档案 — 张铧心互动作品集",
      "五个 Csikos Post 录音版本分别塑造五种关卡风格",
      "技术：Next.js、Phaser 3、Web Audio",
    ],
  },
  hud: {
    pause: "暂停",
    resume: "继续",
    sound: "声音",
    archive: "档案",
    skip: "跳过章节",
    assist: "辅助",
    explore: "浏览",
    combo: "连击",
    memory: "记忆",
  },
  chapters: {
    prologue: "序章",
    "movement-i": "第一乐章 — Pixel Seed",
    "movement-ii": "第二乐章 — 有用的系统",
    "movement-iii": "第三乐章 — 负责任的对话",
    "movement-iv": "第四乐章 — 可解释的信号",
    coda: "尾声",
  },
  narrative: {
    "prologue-1": "每个项目都始于一个信号。",
    "prologue-2": "有些成为系统。",
    "prologue-3": "有些成为世界。",
    "prologue-4": "我让复杂系统变得可感知、可游玩、可追责。",
    "pixel-1": "空白琴键等待一句提示。",
    "pixel-2": "形态从意图中汇聚。",
    "pixel-3": "世界不是一张图 — 它是你可以进入的地方。",
    "pixel-4": "Pixel Seed：从提示到可玩舞台。",
    "browser-1": "你清掉了噪音。",
    "browser-2": "有用的信号一直都在。",
    "browser-3": "我设计浏览器工具，把重复动作变成有意图的工作流。",
    "emotion-1": "不是每个信号都需要被纠正。",
    "emotion-2": "有些需要被听见。",
    "emotion-3": "体贴的系统知道何时回应 — 也知道何时留白。",
    "research-1": "原始信号很少自我解释。",
    "research-2": "模式在仔细的提问中浮现。",
    "research-3": "研究教会我看见界面之外。",
    "coda-1": "线索回到同一件乐器。",
    "coda-2": "若这段体验留下了信号，让我们继续对话。",
  },
  explore: {
    title: "精选作品",
    subtitle: "产品决策、工作系统，以及支撑它们的证据。",
    about: "关于",
    projects: "项目",
    contact: "联系",
    downloadCv: "下载简历",
    playInstead: "演奏作品集",
  },
  contact: {
    email: "hxz439@alumni.bham.ac.uk",
    github: "https://github.com/zbjgrhr",
    cvPath: "/downloads/Huaxin_Zhang_CV.docx",
    portfolioPath: "/downloads/Zhang_Huaxin_Creative_Portfolio.pdf",
  },
  coda: {
    title: "一起建造有意义的事",
    line: "若这段体验留下了信号，让我们继续对话。",
    replay: "再演奏一次",
    explore: "浏览项目",
    autoplay: "开启自动演奏",
  },
  archive: {
    close: "关闭档案",
    context: "背景",
    problem: "问题",
    role: "我的角色",
    process: "过程",
    decisions: "关键决策",
    tech: "技术",
    challenges: "挑战",
    outcome: "结果",
    learned: "我学到的",
    links: "链接",
  },
  pauseMenu: {
    title: "已暂停",
    resume: "继续",
    settings: "设置",
    exitExplore: "退出到浏览",
  },
};
